language: java
# use Java 8
jdk:
- oraclejdk8

# faster builds
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2

script: 
- mvn clean package # azure-webapp:deploy

before_deploy:
 - "echo 'Redo? Nu kommer det?'"
 # - mv .gitignore.production .gitignore
deploy:
 provider: azure_web_apps
 verbose: true
 skip_cleanup: true

